# -*- coding: utf-8 -*-
"""Kariagina "PythonUrban_lab2.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OU4GwkAU8-4XMd6-Nn5JkH1aOEFLPS-y

# Итоговый проект. Улицы. Объекты культурного наследия.
"""

# TODO собрать установку всех необходимых модулей в одном месте
!pip install geopandas 
!pip install mapclassify
!pip install osmnx

# TODO собрать импорты всех модулей в одном месте
import geopandas as gpd
import osmnx as ox
import pandas as pd

TILES = "CartoDB positron"  # Название подложки для карт

# TODO указать любой район Санкт-Петербург из OSM https://wiki.openstreetmap.org/wiki/RU:%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3/%D0%A0%D0%B0%D0%B9%D0%BE%D0%BD%D1%8B
TERRITORY_NAME = "Красногвардейский район, Санкт-Петербург"  # название территории для которой будут строиться слои

# TODO указать ссылку на файл из вашего github репозитория, которая начинается с https://raw.githubusercontent.com/
KGIOP_FILE_URL = "https://raw.githubusercontent.com/alksndraqn/UrbanPython2022/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/kgiop_objects.geojson"  # ссылка на слой с объектами культурного наследия
STREETS_FILE_URL = "https://raw.githubusercontent.com/alksndraqn/UrbanPython2022/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/streets.geojson"  # ссылка на слой с улицами

"""## Территория

### Загрузка территории из OSM (Extract)
"""

# TODO загрузить geodataframe с геометрией для территории TERRITORY_NAME
district = ox.geocode_to_gdf(TERRITORY_NAME)
district.explore(tiles="CartoDB positron")

"""## Улицы

### Загрузка файла с улицами (Extract)
"""

# TODO отфильтровать улицы по маске геометрии территории полученной ранее

gdf_street = gpd.read_file(STREETS_FILE_URL, mask=district)
gdf_street

"""### Обработка данных с улицами (Transform)"""

# TODO сгруппировать и объединить геометрии с одинаковыми названиями
#gdf_street["name"].is_unique
gdf_street = gdf_street.dissolve(by="name").reset_index() #не работал шаг с переименованием столбца без индекс ресета, не удавалось даже отобразить столбец по его имени
gdf_street

"""### Сохранение слоя с улицами (Load)"""

# TODO переименовать столбцы в русские названия, кроме столбца geometry
# TODO для того чтобы переименовать индекс, нужно обратиться и нему и вызвать от него метод rename (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.rename.html)
gdf_street.rename(columns={'name':'название улицы'},inplace=True)
gdf_street

# TODO сохранить слой в географической проекции в формате GeoJSON
gdf_street.to_crs(4326).to_file('union_streets.geojson', driver='GeoJSON')

"""## Объекты культурного наследия

### Загрузка объектов культурного наследия (Extract)
"""

# TODO отфильтровать улицы по маске геометрии территории полученной ранее
gdf_OKN = gpd.read_file(KGIOP_FILE_URL, mask=district)
gdf_OKN

"""### Обработка объектов культурного наследия (Transform)"""

# TODO добавить два столбца lon и lat, в которых будут долгота и широта 
gdf_OKN['lot'] = gdf_OKN.to_crs(3857).geometry.centroid.to_crs(4326).x
gdf_OKN['lat'] = gdf_OKN.to_crs(3857).geometry.centroid.to_crs(4326).y
gdf_OKN

"""### Сохранение слоя с объектами культурного наследия (Load)"""

# TODO переименовать столбцы в русские названия, кроме столбца geometry
rename_columns = {
    "id": "Идентификатор",
    "ensemble_name": "Наименование ансамбля",
    "object_name": "Наименование объекта",
    "occurrence_time": "Время возникновения",
    "object_location": "Расположение",
    "historical_category": "Категория",
    "normative_act": "Нормативно-правовой акт",
    "object_type": "Тип ОКН",
    "lot": "Долгота",
    "lat": "Широта"
}
gdf_OKN.rename(columns=rename_columns, inplace=True)
gdf_OKN

# TODO сохранить слой в географической проекции в формате GeoJSON
gdf_OKN.to_crs(4326).to_file('renamed_OKN.geojson', driver='GeoJSON')

